# Generated by Django 4.1.3 on 2023-01-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='status',
            field=models.CharField(choices=[('WAITING', 'در انتظار بازدید'), ('VISIT', 'بازدید انجام شده است')], max_length=20, verbose_name='وضعیت'),
        ),
    ]
