# Generated by Django 4.1.3 on 2023-01-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_contact_module', '0002_alter_usercontact_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='customer',
        ),
        migrations.AddField(
            model_name='usercontact',
            name='customer_phone_number',
            field=models.PositiveBigIntegerField(default=9100000000, verbose_name='شماره مشتری'),
            preserve_default=False,
        ),
    ]
