# Generated by Django 4.1.3 on 2023-01-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_contact_module', '0003_remove_usercontact_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='status',
            field=models.CharField(choices=[('CLUE', 'سرنخ'), ('EVALUATED', 'ارزیابی شده'), ('INTRODUCED', 'معرفی شده'), ('SERVICED_PROVIDED', 'سرویس داده شده'), ('NEGOTIATED', 'مذاکره شده'), ('MEETING', 'جلسه گذاشته شد'), ('CONTRACTING', 'قرار داد بسته شد'), ('CANCELED', 'لغو شد')], max_length=20, verbose_name='وضعیت'),
        ),
    ]
