# Generated by Django 4.1.3 on 2023-01-09 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate_module', '0012_estate_fav_of_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن / نبودن')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حدف شده / نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین اپدیت')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('amount', models.PositiveBigIntegerField(verbose_name='درآمد')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_module.estate', verbose_name='ملک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درآمد ها',
            },
        ),
    ]
