# Generated by Django 4.1.3 on 2023-01-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_income_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'verbose_name': 'درآمد', 'verbose_name_plural': 'درآمد ها'},
        ),
    ]
