# Generated by Django 4.1.3 on 2022-11-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_number_verified',
            field=models.BooleanField(default=False, verbose_name='شماره تلفن تایید شده/نشده'),
        ),
    ]
