# Generated by Django 4.1.3 on 2022-11-24 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_verificationcode_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=4, verbose_name='کد تایید'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 13, 38, 38, 109135, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضا'),
        ),
    ]
