# Generated by Django 4.1.3 on 2022-11-24 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_alter_verificationcode_code_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 14, 27, 0, 58403, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضا'),
        ),
    ]
