# Generated by Django 4.1.3 on 2022-11-27 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_alter_user_managers_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_consultant',
            field=models.BooleanField(default=False, verbose_name='وضعیت مشاور بودن / نبودن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_number_verified',
            field=models.BooleanField(default=False, verbose_name='شماره تلفن تایید شده / نشده'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 17, 55, 2, 43952, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضا'),
        ),
    ]
