# Generated by Django 4.1.3 on 2022-12-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(verbose_name='تاریخ انقضا'),
        ),
    ]
