# Generated by Django 4.1.3 on 2022-12-07 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن / نبودن')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حدف شده / نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین اپدیت')),
                ('image', models.ImageField(upload_to='estates/', verbose_name='تصویر ملک')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstateProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن / نبودن')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حدف شده / نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین اپدیت')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('icon', models.ImageField(upload_to='estates/properties/', verbose_name='آیکن')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن / نبودن')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حدف شده / نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین اپدیت')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='estate_module.estatecategory', verbose_name='والد')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی های ملک',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن / نبودن')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حدف شده / نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین اپدیت')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('latitude', models.FloatField(verbose_name='طول جغرافیایی')),
                ('longitude', models.FloatField(verbose_name='عرض جغرافیایی')),
                ('number_of_rooms', models.PositiveIntegerField(verbose_name='تعداد اتاق ها')),
                ('floor', models.PositiveIntegerField(verbose_name='طبقه')),
                ('meterage', models.PositiveIntegerField(verbose_name='متراژ')),
                ('is_special', models.BooleanField(default=False, verbose_name='آگهی ویژه')),
                ('category', models.ManyToManyField(to='estate_module.estatecategory', verbose_name='دسته بندی')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('estate_properties', models.ManyToManyField(to='estate_module.estateproperty', verbose_name='ویژگی ها')),
                ('images', models.ManyToManyField(to='estate_module.estateimage', verbose_name='تصاویر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
