# Generated by Django 4.1.3 on 2022-12-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0001_initial'),
    ]

    operations = [
    ]
