# Generated by Django 4.1.3 on 2022-12-04 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': 'ملک', 'verbose_name_plural': 'املاک'},
        ),
        migrations.AlterField(
            model_name='estate',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_ladder',
            field=models.BooleanField(default=False, verbose_name='نردبان بودن / نبودن'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='ویژه بودن / نبودن'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='latitude',
            field=models.FloatField(verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='longitude',
            field=models.FloatField(verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='meterage',
            field=models.PositiveIntegerField(verbose_name='متراژ'),
        ),
    ]
