# Generated by Django 4.1.3 on 2022-12-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0002_auto_20221207_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': 'ملک', 'verbose_name_plural': 'ملک ها'},
        ),
        migrations.AlterModelOptions(
            name='estatecategory',
            options={'verbose_name': 'دسته بندی ملک', 'verbose_name_plural': 'دسته بندی های ملک'},
        ),
        migrations.AlterModelOptions(
            name='estateimage',
            options={'verbose_name': 'تصویر ملک', 'verbose_name_plural': 'تصویر های ملک'},
        ),
        migrations.AlterModelOptions(
            name='estateproperty',
            options={'verbose_name': 'ویژگی ملک', 'verbose_name_plural': 'ویژگی های ملک'},
        ),
        migrations.AddField(
            model_name='estate',
            name='ad_type',
            field=models.CharField(choices=[('R', 'اجاره'), ('S', 'فروش')], default='S', max_length=10, verbose_name='نوع آگهی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='deposit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ودیعه'),
        ),
        migrations.AddField(
            model_name='estate',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='estate',
            name='price',
            field=models.BigIntegerField(default=100000, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
