# Generated by Django 4.1.3 on 2022-12-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0003_alter_estate_options_alter_estatecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='estate_properties',
            field=models.ManyToManyField(blank=True, to='estate_module.estateproperty', verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='images',
            field=models.ManyToManyField(blank=True, to='estate_module.estateimage', verbose_name='تصاویر'),
        ),
    ]
