# Generated by Django 4.1.3 on 2022-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0004_alter_estate_estate_properties_alter_estate_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='build_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AddField(
            model_name='estate',
            name='ladder',
            field=models.BooleanField(default=False, verbose_name='نردبون'),
        ),
    ]
