# Generated by Django 4.1.3 on 2022-12-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0005_estate_build_date_estate_ladder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='ladder',
            new_name='is_ladder',
        ),
    ]
