# Generated by Django 4.1.3 on 2022-12-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0006_rename_ladder_estate_is_ladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
