# Generated by Django 4.1.3 on 2022-12-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0008_estate_last_ladder_updated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='category',
        ),
        migrations.DeleteModel(
            name='EstateCategory',
        ),
        migrations.AddField(
            model_name='estate',
            name='category',
            field=models.CharField(blank=True, choices=[('ٰV', 'ویلایی'), ('A', 'آپارتمانی')], max_length=9, null=True, verbose_name='دسته بندی'),
        ),
    ]
