# Generated by Django 4.1.3 on 2022-12-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0009_remove_estate_category_delete_estatecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='category',
            field=models.CharField(blank=True, choices=[('V', 'ویلایی'), ('A', 'آپارتمانی')], max_length=9, null=True, verbose_name='دسته بندی'),
        ),
    ]
