# Generated by Django 4.1.3 on 2022-12-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0010_alter_estate_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='expire_date',
        ),
    ]
