# Generated by Django 4.1.3 on 2022-12-31 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate_module', '0011_remove_estate_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='fav_of_users',
            field=models.ManyToManyField(blank=True, related_name='fav_of_users', to=settings.AUTH_USER_MODEL, verbose_name='مورد علاقه'),
        ),
    ]
