# Generated by Django 4.1.3 on 2023-01-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0013_estate_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='category',
            field=models.CharField(blank=True, choices=[('RESIDENTIAL', 'مسکونی'), ('BUSINESS', 'تجاری'), ('VILLA', 'ویلایی'), ('REAL_ESTATE', 'املاک و مستغلات')], max_length=15, null=True, verbose_name='دسته بندی'),
        ),
    ]
