# Generated by Django 4.1.3 on 2023-01-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0014_alter_estate_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن / نبودن')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حدف شده / نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین اپدیت')),
                ('title', models.CharField(max_length=300, verbose_name='منطقه')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'منطقه ها',
            },
        ),
        migrations.AddField(
            model_name='estate',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estate_module.estateregion', verbose_name='منطقه'),
        ),
    ]
