# Generated by Django 4.1.3 on 2023-01-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0015_estateregion_estate_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateregion',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
    ]
