# Generated by Django 4.1.3 on 2023-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_module', '0016_alter_estateregion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='category',
            field=models.CharField(blank=True, choices=[('RESIDENTIAL', 'مسکونی'), ('BUSINESS', 'تجاری'), ('OFFICIAL', 'اداری'), ('VILLA', 'ویلایی'), ('KOLANGI', 'کلنگی'), ('REAL_ESTATE', 'مستغلات')], max_length=15, null=True, verbose_name='دسته بندی'),
        ),
    ]
